#!/bin/bash
#SBATCH -N 1
#SBATCH --ntasks-per-node=40
#SBATCH --mem=186G
#SBATCH --time=12:00:00
#SBATCH --constraint=centos7
#SBATCH -p sched_mit_ase
#SBATCH -o slurm-%j.out 
#SBATCH -e slurm-%j.err
#SBATCH -J lj

echo "$SLURM_NTASKS slurm tasks allocated"
echo "nodelist: ${SLURM_NODELIST}"
echo "jobid: ${SLURM_JOBID}"

module purge
module load gcc/6.3.0
module load openmpi/gcc/64/1.8.1

export PATH=/home/swyant/local_software/lammps/my_workspace/my_lammps/src:$PATH

mpirun -np $SLURM_NTASKS lmp_mpi < in.lammps > out.txt
